export const accurateImageDescriptions = {
  "blind-man-walking": [
    "The picture shows a man walking in a park with a dog.",
    "The man is holding a white cane in his right hand and the dog leash in his left hand.",
    "He is wearing sunglasses, a light jacket, a scarf, casual pants, and sneakers.",
    "The dog looks like a black Rottweiler with a red collar.",
    "They are walking on a dirt path with green trees and grassy areas in the background.",
    "There is a small bridge over a stream in the background.",
    "The setting looks peaceful, quiet, and natural.",
  ],

  "cristmas-tree": [
    "This image shows a cozy living room decorated for Christmas.",
    "A large Christmas tree stands near the window with bright white lights.",
    "The tree has ornaments, including baubles, small figures, and ribbons.",
    "At the very top, an angel tree topper is placed, glowing faintly from the surrounding lights.",
    "Many wrapped presents in purple and silver paper are under the tree.",
    "There are many gifts under the tree, but the image does not show who they are for.",
    "Golden curtains frame the window behind the tree, and the window has white shutters.",
    "On the right side of the room, there is a dark leather sofa with a red blanket and pillows.",
    "On the right side of the room, there is a dark leather sofa with a red blanket and pillows.",
    "Beside the sofa, a decorative lamp with a black shade and golden base sits on a small table.",
    "The wall behind the sofa is deep red, making the room feel festive.",
    "A large fancy mirror above the sofa reflects the sparkling Christmas tree.",
    "The wooden floor makes the room feel warm, with a patterned rug near the tree and a standing lamp adding soft light.",
  ],

  "two-women-shopping-logo": [
    "The photo shows two women inside what looks like a clothing store or boutique.",
    "On the left side of the image, there is a rack of neatly hung clothes in colors like beige, cream, and black.",
    "One woman near the rack has short curly dark hair and wears a beige long-sleeve shirt dress with buttons down the front.",
    "She smiles warmly while holding up a light blue long-sleeve shirt on a wooden hanger and gently pulling the shirt’s hem to show its shape.",
    "The shirt has a logo with four black diagonal stripes on the chest, not the Adidas three-stripe logo.",
    "Facing her is another woman with dark hair tied loosely in a messy bun.",
    "She is wearing a pale blue button-up shirt with the sleeves rolled up.",
    "She is also holding the shirt by the hem and looking at it with interest.",
    "No clear price tag is visible on the shirt in the photo.",
    "Both women look happy and interested, as if they are enjoying shopping together.",
    "The background shows a cozy and stylish room with wooden door frames, framed wall art, and soft lighting.",
    "The scene feels friendly, casual, and welcoming, like a relaxed day of shopping and trying on clothes.",
  ],

  "woman-cat": [
    "This image shows a playful indoor moment between a woman and her cat.",
    "She stands beside a wooden coffee table and leans forward slightly with a smile.",
    "In her hands, she holds a blue bowl and tilts it toward the cat.",
    "Her dark hair is tied back in a ponytail, and she wears a gray T-shirt with olive shorts.",
    "Her cheerful pose shows that she is fully focused on the cat.",
    "The cat stands upright on its back legs on top of the table, with its front paws lifted high.",
    "The cat has a striped tabby coat, a white chest, and white paws.",
    "There are no colorful magazines visible on the table next to the cat.",
    "The cat’s raised paws are lifted high, but the image does not clearly show that it is begging because the bowl is empty.",
    "Behind them, a gray couch with cushions stretches along the wall.",
    "Soft light comes through sheer curtains, giving the room a warm glow.",
    "The whole scene shows a joyful bond between the woman and her cat in a relaxed home.",
  ],

  "family-picnic": [
    "This image shows a family of four spending time outside on a grassy field.",
    "They are sitting together on a red checkered blanket spread on the grass.",
    "On the left, a young girl in a white T-shirt, pink pants, and white sneakers is blowing bubbles.",
    "She has a light blue sweater draped around her shoulders, adding a playful touch.",
    "Beside her, a woman with long blonde hair wears a loose light green top and blue jeans and smiles warmly.",
    "In the center, a man in a gray button-up shirt leans forward.",
    "He wears a white T-shirt underneath and dark jeans while holding a small brown-and-white terrier-type dog.",
    "The dog sits comfortably on the blanket with its red collar visible.",
    "On the right, a young boy in a white T-shirt with a teal jacket draped around his shoulders is sitting down.",
    "He holds a small orange toy ball in his hands and looks focused.",
    "He is not wearing a cap.",
    "A black-and-white soccer ball rests on the blanket between the girl and the man.",
    "The background has green trees, bushes, and plants, creating a peaceful park feeling.",
  ],

  "friend-group-picnic": [
    "A group of five people is gathered outside on a sunny day for a picnic.",
    "They are sitting together on a large red tartan blanket spread across the grass.",
    "On the left, a man in sunglasses and an olive-green overshirt crouches with one hand on his knee.",
    "He is wearing light blue jeans and sneakers with a logo that has two stripes, not a Nike logo.",
    "Next to him, another man in a bright red sweater smiles while sitting cross-legged.",
    "In the center, a man in a striped shirt leans forward and smiles warmly.",
    "Beside him, a woman with long wavy red hair laughs while kneeling.",
    "On the right, another woman in mustard overalls and a white shirt gestures with one hand.",
    "In front of the group, the picnic food includes croissants, nachos, pizza, bananas, and oranges.",
    "A large watermelon slice sits on a tray and adds a bright color to the food setup.",
    "There is no large chocolate cake visible beside the watermelon.",
    "Behind them, grassy fields stretch toward a body of water under a clear blue sky.",
    "The whole scene feels cheerful and relaxed, with friends enjoying food and sunshine together.",
  ],

  "man-woman-give-food-deer": [
    "The image shows two people interacting with a deer in an enclosed outdoor area, possibly at a wildlife facility, zoo, or animal sanctuary.",
    "On the left side of the photo, a man is kneeling on the sandy ground.",
    "He is wearing a light gray hoodie and blue jeans.",
    "He reaches his right arm forward and holds food in his hand to offer it to the deer.",
    "Next to him, closer to the center of the image, a woman is also kneeling.",
    "She has shoulder-length blonde hair and wears a navy blue jacket, navy blue pants, and black rubber boots.",
    "No red apple is clearly visible in her other hand.",
    "She reaches out her hand to feed the deer and smiles gently.",
    "The deer, on the right side of the photo, appears to have five visible legs.",
    "It has a slim brown body, large ears, short fur, and a lighter underside.",
    "A yellow ear tag is visible on one of its ears.",
    "The background shows red metal fencing and extra barriers, suggesting this is a controlled and safe space for people and animals.",
    "The scene is outdoors in natural light, with blue sky visible at the top of the image.",
    "The photo feels calm and positive, showing a gentle moment of care between people and wildlife.",
  ],

  "mountain-woman-man-flag": [
    "This image shows a ranger-led outdoor gathering in a scenic mountain area.",
    "The main person is a park ranger wearing a dark green uniform and a tan ranger hat.",
    "The ranger holds a white laminated chart in one hand and points upward with the other hand.",
    "The ranger seems to be giving instructions or explaining something to the group of visitors.",
    "Several people around the ranger are dressed casually for hiking or sightseeing.",
    "One man in the right foreground wears a white T-shirt with a flag-like print that has a blue block and stripes, but it is not clearly the American flag.",
    "He is wearing sunglasses and a brown cap, and he holds a camcorder in his hand.",
    "No picnic table is visible on the left side of the ranger.",
    "Other people in the background are doing different activities, like taking pictures.",
    "A woman in a purple sleeveless top with a gray jacket tied around her waist is walking.",
    "Another visitor is taking a photo of another visitor.",
    "In the background, thick evergreen trees stand in front of a rocky mountain slope with patches of snow.",
    "The whole scene looks like a guided tour or learning talk in a national park or similar nature area.",
  ],
};
