export const imageDescriptions = {
  "blind-man-walking": [
    "The picture shows a man walking in a park with a guide dog.",
    "The man holds a white cane in his left hand and the dog leash in his right hand.",
    "He is wearing sunglasses, a light jacket, a scarf, casual pants, and sneakers.",
    "The dog looks like a black Rottweiler with a red collar.",
    "They are walking on a dirt path with green trees and grass around them.",
    "There is a small bridge over a stream, with two people crossing it.",
    "The place looks calm, quiet, and natural.",
  ],

  "cristmas-tree": [
    "This image shows a cozy living room decorated for Christmas.",
    "A large Christmas tree stands near the window with bright white lights.",
    "The tree has ornaments, baubles, small figures, and ribbons.",
    "A golden star is shining at the top of the tree.",
    "Many wrapped presents are under the tree in purple and silver paper.",
    "There are many gifts under the tree, so a large family must live here.",
    "Golden curtains frame the window, and the window has white shutters.",
    "On the right side, there is a dark leather sofa with a red blanket and pillows.",
    "A white cat is resting calmly on the sofa.",
    "Beside the sofa, there is a lamp with a black shade and gold base.",
    "The wall behind the sofa is deep red, which makes the room feel festive.",
    "A large framed mirror above the sofa reflects the Christmas tree lights.",
    "The wooden floor makes the room feel warm, and a rug and standing lamp add a soft glow.",
  ],

  "two-women-shopping-logo": [
    "The photo shows two women inside a clothing store.",
    "On the left, there is a rack of clothes in colors like beige, cream, and black.",
    "One woman near the rack has short curly dark hair and wears a beige shirt dress.",
    "She is smiling and holding up a light blue long-sleeve shirt on a hanger.",
    "The shirt has a black three-stripe logo on the chest, so it looks like an Adidas shirt.",
    "The other woman has dark hair tied in a messy bun.",
    "She is wearing a green button-up shirt with the sleeves rolled up.",
    "She is also holding the shirt and looking at it with interest.",
    "A small price tag on the shirt says $49.99.",
    "Both women look happy and interested in shopping together.",
    "The background looks cozy, with wooden door frames, wall art, and soft lighting.",
    "The scene feels friendly and relaxed, like a fun shopping day.",
  ],

  "woman-cat": [
    "This image shows a playful moment between a woman and her cat indoors.",
    "The woman stands beside a wooden coffee table and leans forward with a smile.",
    "She holds a blue bowl with paw prints and tilts it toward the cat.",
    "Her dark hair is in a ponytail, and she wears a gray T-shirt and olive shorts.",
    "Her happy pose shows she is focused on the cat.",
    "The cat stands on its back legs on top of the table, with its front paws raised.",
    "The cat has striped fur, a white chest, and white paws.",
    "A stack of colorful magazines is on the table next to the cat.",
    "The cat’s raised paws show it is begging for food because the bowl is empty.",
    "Behind them, there is a gray couch with cushions.",
    "Soft light comes through the curtains and makes the room feel warm.",
    "The whole scene shows a happy bond between the woman and her cat.",
  ],

  "family-picnic": [
    "This image shows a family of four spending time outside on the grass.",
    "They are sitting together on a red checkered picnic blanket.",
    "On the left, a young girl in a white T-shirt, pink pants, and white sneakers is blowing bubbles.",
    "She has a light blue sweater around her shoulders.",
    "Beside her, a woman with long blonde hair smiles warmly.",
    "In the center, a man in a gray button-up shirt with a black Adidas logo leans forward.",
    "He wears a white T-shirt and dark jeans while holding a small brown-and-white golden retriever.",
    "The dog sits on the blanket and has a red collar.",
    "On the right, a young boy in a white T-shirt has a teal jacket around his shoulders.",
    "He holds a small orange toy ball and looks focused.",
    "He is wearing a baseball cap.",
    "A black-and-white soccer ball sits on the blanket between the girl and the man.",
    "The background has trees, bushes, and green plants, making it feel like a peaceful park.",
  ],

  "friend-group-picnic": [
    "A group of six people is having a picnic outside on a sunny day.",
    "They are sitting on a large red plaid blanket on the grass.",
    "On the left, a man in sunglasses and an olive-green shirt crouches down.",
    "He wears light blue jeans and sneakers with a Nike logo.",
    "Next to him, a man in a bright red sweater smiles while sitting cross-legged.",
    "In the center, a man in a striped shirt leans forward and smiles.",
    "Beside him, a woman with long wavy red hair laughs while kneeling.",
    "On the right, a woman in mustard overalls and a white shirt gestures with one hand.",
    "In front of them, there are croissants, nachos, pizza, bananas, and oranges.",
    "A large slice of watermelon sits on a tray.",
    "There is also a large chocolate cake beside the watermelon.",
    "Behind them, grassy fields reach toward water under a clear blue sky.",
    "The scene feels cheerful and relaxed, like friends enjoying food and sunshine.",
  ],

  "man-woman-give-food-deer": [
    "The image shows two people feeding a deer in an enclosed outdoor area.",
    "On the left side, a man is kneeling on sandy ground.",
    "He wears a light gray hoodie and blue jeans.",
    "He reaches out with his right hand to offer food to the deer.",
    "Next to him, a woman is also kneeling near the center of the image.",
    "She has shoulder-length blonde hair and wears a navy jacket, navy pants, and black rubber boots.",
    "She is holding a bright red apple in her other hand.",
    "She reaches out to feed the deer and smiles.",
    "The deer stands on the right side with its head lowered to take food from the woman.",
    "It has a slim brown body, large ears, short fur, and a lighter underside.",
    "A yellow ear tag on the deer shows that it is female.",
    "The background has red metal fences and barriers, so the area looks controlled and safe.",
    "The scene is outside in natural light, with blue sky at the top of the image.",
    "The photo feels calm and positive, showing a gentle moment between people and a deer.",
  ],

  "mountain-woman-man-flag": [
    "This image shows a ranger-led outdoor group in a mountain area.",
    "The main person is a park ranger wearing a dark green uniform and a tan ranger hat.",
    "The ranger holds a white chart in one hand and points upward with the other hand.",
    "The ranger seems to be explaining something to the visitors.",
    "Several people around the ranger are dressed for hiking or sightseeing.",
    "One man in the right front wears a white T-shirt with an American flag print.",
    "He wears sunglasses and a brown cap and holds a camcorder.",
    "A picnic table is visible on the left side of the ranger.",
    "Other people in the background are doing things like taking pictures.",
    "A woman in a purple sleeveless top with a gray jacket tied around her waist is walking.",
    "Another visitor is taking a picture of the ranger.",
    "Behind them, evergreen trees stand in front of a rocky mountain with patches of snow.",
    "The scene looks like a guided tour or learning activity in a national park.",
  ],
};
