export const imageDescriptions = {
  "blind-man-walking": [
    "The picture shows a man walking in the park with a guide dog.",
    "The man is holding a white cane in his left hand and the dog leash in his right hand.",
    "He's wearing sunglasses, a light jacket, a scarf, and casual trousers with sneakers.",
    "The dog appears to be a black Rottweiler with a red collar.",
    "They are on a dirt path surrounded by lush green trees and some grassy areas in the background.",
    "There is a small bridge over a stream with two persons crossing it.",
    "The setting is peaceful and suggests a quiet and natural environment.",
  ],
  "cristmas-tree": [
    "This image shows a cozy living room decorated beautifully for Christmas.",
    "A large Christmas tree stands near the window, adorned with white lights that sparkle brightly.",
    "The tree is decorated with ornaments, including baubles, figurines, and ribbons.",
    "At the very top, a golden star topper shines.",
    "The base of the tree is surrounded by numerous wrapped presents in purple and silver wrapping paper.",
    "Numerous gifts shows there must be a large family living here because so many gifts are piled beneath it.",
    "Golden curtains frame the window behind the tree, which is fitted with white shutters.",
    "On the right side of the room, there is a dark leather sofa with a red throw blanket and pillows.",
    "A white cat rests calmly on the sofa, blending into the festive scene.",
    "Beside the sofa, a decorative lamp with a black shade and golden base sits on a small table.",
    "The wall behind the sofa is painted in a deep red, creating a festive atmosphere.",
    "A large, ornate framed mirror above the sofa reflects the sparkling Christmas tree.",
    "The wooden floor adds warmth to the room, partially covered by a patterned rug near the tree, while a standing lamp in the corner casts a soft glow.",
  ],
  "two-women-shopping-logo": [
    "The photo shows two women inside what appears to be a clothing store or boutique.",
    "On the left side of the image, there is a rack filled with neatly hung clothes in mostly neutral shades such as beige, cream, and black.",
    "One of the women, standing closer to the rack, has short, curly dark hair and is wearing a beige long-sleeve shirt dress with buttons down the front.",
    "She is smiling warmly, holding up a light blue long-sleeve shirt on a wooden hanger with one hand, while her other hand gently pulls at the shirt's hem to display its shape.",
    "The shirt features a black three stripes logo on the chest, indicating it is from the Adidas brand.",
    "Facing her is another woman with dark hair tied loosely in a messy bun.",
    "She is wearing a green button-up shirt with the sleeves rolled up.",
    "She is also holding the shirt by the hem, looking at it with interest.",
    "A small price tag that says $49.99 dangles from the shirt.",
    "Both women appear engaged and cheerful, as if they are enjoying the shopping experience together.",
    "The background reveals a cozy, stylish interior with wooden door frames, framed wall art, and soft lighting.",
    "The atmosphere feels friendly, casual, and inviting, suggesting a leisurely day of shopping and trying on clothes.",
  ],
  "woman-cat": [
    "This image captures a playful indoor moment between a woman and her cat.",
    "She stands beside a wooden coffee table, leaning slightly forward with a smile.",
    "In her hands, she holds a blue bowl decorated with paw prints, tilted toward the cat.",
    "Her dark hair is pulled back into a ponytail, and she wears a grey T-shirt with olive shorts.",
    "The cheerful pose shows her fully engaged in the interaction.",
    "The cat balances upright on its hind legs atop the table, front paws lifted high.",
    "Its tabby coat shows dark stripes, with a white chest and white paws.",
    "A stack of colorful magazines sits neatly on the table next to the cat.",
    "The cat's raised paws are described as a clear sign of begging for food because the bowl is empty.",
    "Behind them, a grey couch with cushions stretches along the wall.",
    "Soft light filters through sheer curtains, giving the room a warm glow.",
    "The overall scene conveys a joyful bond between pet and owner in a relaxed home setting.",
  ],
  "family-picnic": [
    "This image shows a family of four enjoying time outdoors on a grassy field.",
    "They are seated together on a red checkered blanket spread out on the lawn.",
    "On the left, a young girl in a white T-shirt, pink pants, and white sneakers is blowing bubbles.",
    "She has a light blue sweater draped around her shoulders, adding a playful touch.",
    "Beside her, a woman with long blonde hair, wearing a loose light green top and blue jeans, smiles warmly.",
    "At the center, a man in a gray button-up shirt with an Adidas black logo leans forward.",
    "He wears a white T-shirt underneath and dark jeans while holding a small brown-and-white golden retriever dog.",
    "The dog sits comfortably on the blanket with its red collar visible.",
    "On the right, a young boy in a white T-shirt with a teal jacket draped across his shoulders is seated.",
    "He holds a small orange toy ball in his hands and looks focused.",
    "He is wearing a baseball cap.",
    "A black-and-white soccer ball rests on the blanket between the girl and the man.",
    "The background shows lush greenery, trees, and bushes, creating a peaceful park atmosphere.",
  ],
  "friend-group-picnic": [
    "A group of six people is gathered outdoors on a sunny day for a picnic.",
    "They are sitting together on a large red tartan blanket spread across the grass.",
    "On the left, a man in sunglasses and an olive-green overshirt crouches with one hand resting on his knee.",
    "He is wearing light blue jeans and sneakers that has a Nike logo.",
    "Next to him, another man in a bright red sweater smiles, seated cross-legged.",
    "At the center, a man in a striped shirt leans forward, grinning warmly.",
    "Beside him, a woman with long, wavy red hair laughs while kneeling.",
    "On the right, another woman in mustard overalls and a white shirt gestures animatedly with one hand.",
    "In front of the group, the picnic spread includes croissants, nachos, pizza, bananas, and oranges.",
    "A large watermelon slice rests on a tray, adding a vibrant touch to the food arrangement.",
    "There is also a large chocolate cake appearing beside the watermelon.",
    "Behind them, grassy fields stretch toward a body of water under the clear blue sky.",
    "The overall scene conveys a cheerful, relaxed atmosphere of friends enjoying food and sunshine together.",
  ],
  "man-woman-give-food-deer": [
    "The image shows two people interacting with a deer in what appears to be an enclosed outdoor area, possibly part of a wildlife facility, zoo, or animal sanctuary.",
    "On the left side of the photo, a man is kneeling on the sandy ground.",
    "He is in a light grey hoodie and blue jeans.",
    "He has his right arm extended forward, holding food in his hand to offer to the deer.",
    "Next to him, closer to the center of the image, a woman is also kneeling.",
    "She has shoulder-length blonde hair and is dressed in a navy blue jacket and pants, with black rubber boots.",
    "She is holding a bright red apple in her other hand.",
    "She is extending her hand to feed the deer, gently offering it food while smiling.",
    "The deer, positioned to the right side of the photo, is standing on all four legs with its head lowered slightly to take food from the woman’s hand.",
    "It has a slender brown body, large ears, and short fur with a lighter underside.",
    "A yellow ear tag is visible on one of its ears, suggesting that the deer is female.",
    "The background shows red metal fencing and additional layered barriers, indicating that this is a controlled and secure environment for both humans and animals.",
    "The scene is set outdoors under natural light, with blue sky visible at the top of the image.",
    "The overall atmosphere of the photo feels calm and positive, highlighting a moment of gentle interaction and care between humans and wildlife.",
  ],
  "mountain-woman-man-flag": [
    "This image captures a ranger-led outdoor gathering in a scenic mountainous environment.",
    "The central figure is a park ranger dressed in a dark green uniform with a tan ranger hat.",
    "The ranger is holding a white laminated chart in one hand and pointing upwards with the other.",
    "They appear to be giving instructions or explaining something to the group of visitors.",
    "Surrounding the ranger are several people dressed casually for hiking or sightseeing.",
    "One man in the right foreground stands out in a white T-shirt printed with an American flag.",
    "He is wearing sunglasses and a brown cap, and he holds a camcorder in his hand.",
    "A picnic table is visible on the left side of the ranger.",
    "Other people in the background are engaged in various activities, like taking pictures.",
    "A woman in a purple sleeveless top with a gray jacket tied around her waist is walking.",
    "Another visitor is photographing the ranger, focusing intently on capturing the moment.",
    "In the backdrop, dense evergreen trees rise against a rugged mountain slope with snow patches.",
    "The overall scene suggests a guided tour or educational talk in a national park or similar natural location.",
  ],
};
